library(shiny)
library(readxl)
library(DT)
library(plotly)
library(Hmisc)
library(tseries)
library(lmtest)

source("helpers.R")
source("Modules/genRapport.R")
source("Modules/upload.R")
source("Modules/EDA.R")
source("Modules/DQ.R")
source("Modules/preprocessing.R")
source("Modules/selection.R")
source("Modules/stationnarite.R")
source("Modules/modelling.R")
source("Modules/validation.R")